/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import db.DBKonekcija;
import java.sql.SQLException;
import konfiguracija.Konfiguracija;
import kontroler.KontrolerForme;

/**
 *
 * @author Joca
 */
public class JpnlPodesavanjeBazePodataka extends javax.swing.JPanel {

    FrmServer forma;
    
    /**
     * Creates new form jpnlPodesavanjeBazePodataka
     */
    public JpnlPodesavanjeBazePodataka() {
        initComponents();
        srediPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBazaPodataka = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jtxtDBUsername = new javax.swing.JTextField();
        jtxtDBPassword = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtxtDBNaziv = new javax.swing.JTextField();
        jcmbDBTip = new javax.swing.JComboBox();
        jbtnDBPoveziSe = new javax.swing.JButton();
        jbtnDBTestirajKonekciju = new javax.swing.JButton();
        jlblDBStatus = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jlblerrDBTip = new javax.swing.JLabel();
        jlblerrDBUsername = new javax.swing.JLabel();
        jlblerrDBPassword = new javax.swing.JLabel();
        jlblerrDBNaziv = new javax.swing.JLabel();

        jPanelBazaPodataka.setMinimumSize(new java.awt.Dimension(560, 215));

        jLabel16.setText("Username:");

        jLabel17.setText("Password:");

        jLabel18.setText("Tip baze:");

        jLabel19.setText("Naziv baze:");

        jcmbDBTip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnDBPoveziSe.setText("Povezi se");
        jbtnDBPoveziSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDBPoveziSeActionPerformed(evt);
            }
        });

        jbtnDBTestirajKonekciju.setText("Testiraj konekciju");
        jbtnDBTestirajKonekciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDBTestirajKonekcijuActionPerformed(evt);
            }
        });

        jlblDBStatus.setText(" ");

        jLabel20.setText("Status: ");

        jlblerrDBTip.setText(" ");

        jlblerrDBUsername.setText(" ");

        jlblerrDBPassword.setText(" ");

        jlblerrDBNaziv.setText(" ");

        javax.swing.GroupLayout jPanelBazaPodatakaLayout = new javax.swing.GroupLayout(jPanelBazaPodataka);
        jPanelBazaPodataka.setLayout(jPanelBazaPodatakaLayout);
        jPanelBazaPodatakaLayout.setHorizontalGroup(
            jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBazaPodatakaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBazaPodatakaLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(38, 38, 38)
                        .addComponent(jlblDBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBazaPodatakaLayout.createSequentialGroup()
                        .addComponent(jbtnDBPoveziSe)
                        .addGap(64, 64, 64)
                        .addComponent(jbtnDBTestirajKonekciju))
                    .addGroup(jPanelBazaPodatakaLayout.createSequentialGroup()
                        .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17))
                        .addGap(58, 58, 58)
                        .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBazaPodatakaLayout.createSequentialGroup()
                                .addComponent(jtxtDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlblerrDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBazaPodatakaLayout.createSequentialGroup()
                                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtDBUsername)
                                    .addComponent(jcmbDBTip, 0, 130, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblerrDBTip, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblerrDBUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBazaPodatakaLayout.createSequentialGroup()
                                .addComponent(jtxtDBNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlblerrDBNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelBazaPodatakaLayout.setVerticalGroup(
            jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBazaPodatakaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jcmbDBTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblerrDBTip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtxtDBUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblerrDBUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxtDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblerrDBPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtxtDBNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblerrDBNaziv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDBPoveziSe)
                    .addComponent(jbtnDBTestirajKonekciju))
                .addGap(18, 18, 18)
                .addGroup(jPanelBazaPodatakaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDBStatus)
                    .addComponent(jLabel20))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBazaPodataka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBazaPodataka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDBPoveziSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDBPoveziSeActionPerformed
        // TODO add your handling code here:
        if (izvrsiValidacijuUnetihParametara()) {
            Konfiguracija.vratiInstancu().postaviNaziv(jtxtDBNaziv.getText().trim());
            if (jcmbDBTip.getSelectedIndex() == 1) {
                konfiguracija.Konfiguracija.vratiInstancu().postaviTipDB("access");
            }
            if (jcmbDBTip.getSelectedIndex() == 2) {
                konfiguracija.Konfiguracija.vratiInstancu().postaviTipDB("mysql");
            }
            
            DBKonekcija db = new DBKonekcija();
            try {
                db.otvoriKonekciju(Konfiguracija.vratiInstancu().vratiURL(), jtxtDBUsername.getText().trim(), jtxtDBPassword.getText().trim());
                db.zatvoriKonekciju();
                Konfiguracija.vratiInstancu().postaviUsername(jtxtDBUsername.getText().trim());
                Konfiguracija.vratiInstancu().postaviPassword(jtxtDBPassword.getText().trim());
                Konfiguracija.vratiInstancu().postaviPodesenostBaze("t");
                jlblDBStatus.setText("Uspesno povezivanje sa bazom podataka");
                forma.promeniPanel(1);
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
                jlblDBStatus.setText("Neuspesno povezivanje. Problemi sa ucitavanjem drajvera");
            } catch (SQLException ex) {
                ex.printStackTrace();
                jlblDBStatus.setText("Neuspesno povezivanje");
            }

        }
    }//GEN-LAST:event_jbtnDBPoveziSeActionPerformed

    private void jbtnDBTestirajKonekcijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDBTestirajKonekcijuActionPerformed
        // TODO add your handling code here:
        if (izvrsiValidacijuUnetihParametara()) {
            KontrolerForme.testirajKonekciju(jtxtDBNaziv, jtxtDBUsername, jtxtDBPassword, jcmbDBTip, jlblDBStatus);
        }
    }//GEN-LAST:event_jbtnDBTestirajKonekcijuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanelBazaPodataka;
    private javax.swing.JButton jbtnDBPoveziSe;
    private javax.swing.JButton jbtnDBTestirajKonekciju;
    private javax.swing.JComboBox jcmbDBTip;
    private javax.swing.JLabel jlblDBStatus;
    private javax.swing.JLabel jlblerrDBNaziv;
    private javax.swing.JLabel jlblerrDBPassword;
    private javax.swing.JLabel jlblerrDBTip;
    private javax.swing.JLabel jlblerrDBUsername;
    private javax.swing.JTextField jtxtDBNaziv;
    private javax.swing.JTextField jtxtDBPassword;
    private javax.swing.JTextField jtxtDBUsername;
    // End of variables declaration//GEN-END:variables

    
    
    private void srediPanel() {
        napuniComboTipBaze();
    }

    private void napuniComboTipBaze() {
        jcmbDBTip.removeAllItems();
        jcmbDBTip.addItem("-- Izaberite tip baze podataka --");
        jcmbDBTip.addItem("Access");
        jcmbDBTip.addItem("MySQL");
    }

    private boolean izvrsiValidacijuUnetihParametara() {
        boolean validacija = true;
        if (jcmbDBTip.getSelectedIndex() == 0) {
            jlblerrDBTip.setText("Izabeire tip baze podataka");
            validacija = false;
        } else {
            jlblerrDBTip.setText("");
        }
        if (jtxtDBNaziv.getText().trim().isEmpty()) {
            jlblerrDBNaziv.setText("Unesite naziv");
            validacija = false;
        } else {
            jlblerrDBNaziv.setText("");
        }
        if (jtxtDBUsername.getText().trim().isEmpty()) {
            jlblerrDBUsername.setText("Unesite username");
            validacija = false;
        } else {
            jlblerrDBUsername.setText("");
        }
        if(!validacija){
            jlblDBStatus.setText("Pravilno popunite parametre");
        } else {
            jlblDBStatus.setText("");
        }
        return validacija;
    }

    void postaviFormu(FrmServer aThis) {
        forma = aThis;
    }
}
