/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Film;
import domen.Kopija;
import domen.Osoba;
import domen.Uloga;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import kontroleri.KontrolerKomunikacije;
import modeli.ModelTabeleKopija;
import modeli.ModelTabeleOsoba;
import modeli.ModelTabeleUloga;

/**
 *
 * @author Joca
 */
public class FUnosFilm extends javax.swing.JDialog {
    Film film;
    boolean ponisti = true;
    boolean paziKopije = false;
    /**
     * Creates new form FUnosFilm
     */
    public FUnosFilm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Rectangle bounds = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        this.setBounds(bounds);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtFilmID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtGodinaSnimanja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcomboZanr = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUcesnici = new javax.swing.JTable();
        jbtnObrisiUcesnika = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblOsobe = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jcomboUloga = new javax.swing.JComboBox();
        jbtnSacuvajUcesnika = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblKopije = new javax.swing.JTable();
        jbtnDodajKopiju = new javax.swing.JButton();
        jbtnObrisiKopiju = new javax.swing.JButton();
        jbtnSacuvajFilm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Film ID:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Godina snimanja:");

        jLabel4.setText("Zanr:");

        jcomboZanr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtblUcesnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblUcesnici);

        jbtnObrisiUcesnika.setText("-");
        jbtnObrisiUcesnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiUcesnikaActionPerformed(evt);
            }
        });

        jLabel5.setText("Osobe:");

        jtblOsobe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblOsobe);

        jLabel6.setText("Uloga:");

        jcomboUloga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnSacuvajUcesnika.setText("Sacuvaj Ucesnika");
        jbtnSacuvajUcesnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajUcesnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jcomboUloga, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnSacuvajUcesnika, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(jbtnObrisiUcesnika, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel5)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jbtnObrisiUcesnika)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jbtnSacuvajUcesnika))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Ucesnici", jPanel1);

        jtblKopije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblKopije);

        jbtnDodajKopiju.setText("+");
        jbtnDodajKopiju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajKopijuActionPerformed(evt);
            }
        });

        jbtnObrisiKopiju.setText("-");
        jbtnObrisiKopiju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiKopijuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnDodajKopiju)
                    .addComponent(jbtnObrisiKopiju, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtnDodajKopiju)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnObrisiKopiju))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kopije ", jPanel2);

        jbtnSacuvajFilm.setText("Sacuvaj Film");
        jbtnSacuvajFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtFilmID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtGodinaSnimanja, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcomboZanr, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSacuvajFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtFilmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtGodinaSnimanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcomboZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jbtnSacuvajFilm)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnObrisiUcesnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiUcesnikaActionPerformed
        int rbr = jtblUcesnici.getSelectedRow();
        if (rbr < 0) {
            JOptionPane.showMessageDialog(this, "niste selktovali ucesnika koga bi da obrisete");
        } else {
            Uloga u = ((ModelTabeleUloga) jtblUcesnici.getModel()).vratiUlogu(rbr);
            ((ModelTabeleUloga) jtblUcesnici.getModel()).obrisiUlogu(rbr);
            film.getListaUloga().remove(u);
        }
    }//GEN-LAST:event_jbtnObrisiUcesnikaActionPerformed

    private void jbtnSacuvajUcesnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajUcesnikaActionPerformed
        int rbr = jtblOsobe.getSelectedRow();
        if (rbr < 0) {
            JOptionPane.showMessageDialog(this, "selektujte prvo osobu da biste uneli ulogu");
        } else {
            Osoba o = ((ModelTabeleOsoba) jtblOsobe.getModel()).vratiOsobu(rbr);
            Uloga u = new Uloga();
            u.setNazivUloge((String) jcomboUloga.getSelectedItem());
            switch (u.getNazivUloge()) {
                case "glumi":
                u.setUlogaID("1");
                break;
                case "reziser":
                u.setUlogaID("3");
                break;
                case "reditelj":
                u.setUlogaID("2");
                break;

            }
            u.setOsoba(o);
            u.setFilm(film);
            if (((ModelTabeleUloga) jtblUcesnici.getModel()).vratiListu().contains(u)) {
                JOptionPane.showMessageDialog(this, "uloga vec postoji");
            } else {
                ((ModelTabeleUloga) jtblUcesnici.getModel()).dodajUlogu(u);
                film.getListaUloga().add(u);
            }
        }
    }//GEN-LAST:event_jbtnSacuvajUcesnikaActionPerformed

    private void jbtnDodajKopijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajKopijuActionPerformed
        Film f = new Film();
        f.setFilmID(jtxtFilmID.getText());
        Kopija kopija = new Kopija();
        kopija.setFilm(f);
        kopija.setRbr(KontrolerKomunikacije.vratiRbKopije());
        kopija.setKopijaID(KontrolerKomunikacije.vratiNajveciID(kopija));

        boolean b = KontrolerKomunikacije.sacuvajKopiju(kopija, this);
        if (b == true) {
            List<Kopija> l = KontrolerKomunikacije.vratiListuKopija(this);
            List<Kopija> lista = new ArrayList<>();
            for (Kopija k : l) {
                if (k.getFilm().getFilmID().equals(jtxtFilmID.getText().trim())) {
                    lista.add(k);
                }
            }
            ((ModelTabeleKopija) jtblKopije.getModel()).setListaKopija(lista);
            paziKopije = true;
        }
    }//GEN-LAST:event_jbtnDodajKopijuActionPerformed

    private void jbtnObrisiKopijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiKopijuActionPerformed
        int rbr = jtblKopije.getSelectedRow();
        if (rbr >= 0) {
            Kopija kopija = ((ModelTabeleKopija) jtblKopije.getModel()).vratiKopiju(rbr);
            boolean b = KontrolerKomunikacije.obrisiKopiju(kopija, this);
            if (b == true) {
                ((ModelTabeleKopija) jtblKopije.getModel()).obrisiKopiju(rbr);
                JOptionPane.showMessageDialog(this, "uspesno ste obrisali kopiju");
                if(((ModelTabeleKopija) jtblKopije.getModel()).vratiListu().size()==0){
                    paziKopije = false;
                }
            } else {

            }
        } else {
            JOptionPane.showMessageDialog(this, "selektujte kopiju koju biste da obrisete");
        }
    }//GEN-LAST:event_jbtnObrisiKopijuActionPerformed

    private void jbtnSacuvajFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajFilmActionPerformed

        film.setFilmID(jtxtFilmID.getText());
        film.setZanr((String) jcomboZanr.getSelectedItem());

        if (jtxtNaziv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "unesite naziv filma");
            return;
        } else {
            film.setNaziv(jtxtNaziv.getText());
        }

        if (jtxtGodinaSnimanja.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "unesite godinu snimanja filma");
            return;
        } else {
            if (jtxtGodinaSnimanja.getText().length() > 4) {
                JOptionPane.showMessageDialog(this, "unesite samo GODINU snimanja");
                return;
            } else {
                film.setGodinaSnimanja(Integer.parseInt(jtxtGodinaSnimanja.getText()));
            }
        }

        boolean b = KontrolerKomunikacije.sacuvajFilm(film, this);
        if (b == true) {
            JOptionPane.showMessageDialog(this, "uspesno ste sacuvali film");
            ponisti = false;
            paziKopije = false;
            srediFormu();

        } else {

        }
    }//GEN-LAST:event_jbtnSacuvajFilmActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(paziKopije==true){
            List<Kopija> lista= ((ModelTabeleKopija)jtblKopije.getModel()).vratiListu();
            for (Kopija k : lista) {
//                Film f = new Film();
//                f.setFilmID(jtxtFilmID.getText());
//                k.setFilm(f);
//                System.out.println("ispis kopije u foru"+k);
                KontrolerKomunikacije.odustani(k);
            }
        }
        if(ponisti==true){
            Film f = new Film();
            f.setFilmID(jtxtFilmID.getText());
            KontrolerKomunikacije.odustani(f);
        }
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUnosFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUnosFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUnosFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUnosFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FUnosFilm dialog = new FUnosFilm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnDodajKopiju;
    private javax.swing.JButton jbtnObrisiKopiju;
    private javax.swing.JButton jbtnObrisiUcesnika;
    private javax.swing.JButton jbtnSacuvajFilm;
    private javax.swing.JButton jbtnSacuvajUcesnika;
    private javax.swing.JComboBox jcomboUloga;
    private javax.swing.JComboBox jcomboZanr;
    private javax.swing.JTable jtblKopije;
    private javax.swing.JTable jtblOsobe;
    private javax.swing.JTable jtblUcesnici;
    private javax.swing.JTextField jtxtFilmID;
    private javax.swing.JTextField jtxtGodinaSnimanja;
    private javax.swing.JTextField jtxtNaziv;
    // End of variables declaration//GEN-END:variables
    
    private void popuniComboZanr() {
        jcomboZanr.removeAllItems();
        jcomboZanr.addItem("komedija");
        jcomboZanr.addItem("drama");
        jcomboZanr.addItem("horor");
        jcomboZanr.addItem("akcija");
    }

    private void popuniID() {
        String id = KontrolerKomunikacije.vratiNajveciID(new Film());
        if (!id.startsWith("nije")) {
            jtxtFilmID.setText(id);
            film.setFilmID(id);
        } else {
            System.out.println("nije uspeo da primi id");
        }
    }

    private void srediFormu() {
        jtxtFilmID.setEnabled(false);
        jbtnSacuvajFilm.setVisible(true);
        jtxtGodinaSnimanja.setText("");
        jtxtNaziv.setText("");
        popuniComboZanr();
        popuniComboUloge();
        film = new Film();
        popuniID();
        jtblKopije.setModel(new ModelTabeleKopija());
        jtblOsobe.setModel(new ModelTabeleOsoba(KontrolerKomunikacije.vratiListuOsoba(this)));
        jtblUcesnici.setModel(new ModelTabeleUloga());
        ponisti = true;
    }

    private void popuniComboUloge() {
        jcomboUloga.removeAllItems();
        jcomboUloga.addItem("glumi");
        jcomboUloga.addItem("reziser");
        jcomboUloga.addItem("reditelj");
    }












}
