/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.Film;
import domen.IDomenskiObjekat;
import domen.Kopija;
import domen.Radnici;
import domen.Zaduzenje;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import kontroleri.KontrolerKomunikacije;
import modeli.ModelTabeleKopija;
import modeli.ModelTabeleZaduzenja;

/**
 *
 * @author Joca
 */
public class FUnosZaduzenja extends javax.swing.JDialog {

    /**
     * Creates new form FUnosZaduzenja
     */
    List<Kopija> listaKopija;
    List<Zaduzenje> listaZaduzenja;
    boolean otkazi = false;
    Film film;
    Clan clan;
    Kopija kopija;
    Zaduzenje zaduzenje;

    public FUnosZaduzenja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniFormu();
        Rectangle bounds = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        this.setBounds(bounds);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jcomboClanovi = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jcomboFilmovi = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblKopije = new javax.swing.JTable();
        jPanelTabelaZaduzenja = new javax.swing.JPanel();
        jradioNE = new javax.swing.JRadioButton();
        jradioDA = new javax.swing.JRadioButton();
        jradioSVA = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblZaduzenja = new javax.swing.JTable();
        jbtnIzmeniStatus = new javax.swing.JButton();
        jlbl = new javax.swing.JLabel();
        jtxtDatumRazduzenja = new javax.swing.JTextField();
        jbtnSacuvajIzmenu = new javax.swing.JButton();
        jbtnOtkaziIzmenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbtnOk = new javax.swing.JButton();
        jPanelDodatno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtZaduzenjeID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtDatumZaduzenja = new javax.swing.JTextField();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnOtkazi = new javax.swing.JButton();
        jbtnDodajJos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Clan:");

        jcomboClanovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Film:");

        jcomboFilmovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomboFilmovi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboFilmoviItemStateChanged(evt);
            }
        });

        jtblKopije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblKopije);

        jPanelTabelaZaduzenja.setBorder(javax.swing.BorderFactory.createTitledBorder("Ostala zaduzenja clana"));

        buttonGroup1.add(jradioNE);
        jradioNE.setText("nevracena");

        buttonGroup1.add(jradioDA);
        jradioDA.setText("vracena");

        buttonGroup1.add(jradioSVA);
        jradioSVA.setSelected(true);
        jradioSVA.setText("sva");

        jtblZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblZaduzenja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblZaduzenjaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblZaduzenja);

        jbtnIzmeniStatus.setText("Izmeni status");
        jbtnIzmeniStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniStatusActionPerformed(evt);
            }
        });

        jlbl.setText("Unesite datum razduzenja:");

        jbtnSacuvajIzmenu.setText("Izmeni");
        jbtnSacuvajIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajIzmenuActionPerformed(evt);
            }
        });

        jbtnOtkaziIzmenu.setText("Otkazi izmenu");
        jbtnOtkaziIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOtkaziIzmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabelaZaduzenjaLayout = new javax.swing.GroupLayout(jPanelTabelaZaduzenja);
        jPanelTabelaZaduzenja.setLayout(jPanelTabelaZaduzenjaLayout);
        jPanelTabelaZaduzenjaLayout.setHorizontalGroup(
            jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnIzmeniStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jradioSVA)
                                .addGap(18, 18, 18)
                                .addComponent(jradioDA)
                                .addGap(18, 18, 18)
                                .addComponent(jradioNE))
                            .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jtxtDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jbtnSacuvajIzmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnOtkaziIzmenu)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTabelaZaduzenjaLayout.setVerticalGroup(
            jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioNE)
                    .addComponent(jradioDA)
                    .addComponent(jradioSVA))
                .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jbtnIzmeniStatus)))
                .addGap(48, 48, 48)
                .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl)
                    .addComponent(jtxtDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSacuvajIzmenu)
                    .addComponent(jbtnOtkaziIzmenu))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jLabel5.setText("Kopije");

        jbtnOk.setText("Ok");
        jbtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkActionPerformed(evt);
            }
        });

        jLabel3.setText("Zaduzenje ID:");

        jLabel2.setText("Datum zaduzenja:");

        jbtnSacuvaj.setText("Sacuvaj Zaduzenje");
        jbtnSacuvaj.setRequestFocusEnabled(false);
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDodatnoLayout = new javax.swing.GroupLayout(jPanelDodatno);
        jPanelDodatno.setLayout(jPanelDodatnoLayout);
        jPanelDodatnoLayout.setHorizontalGroup(
            jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDodatnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDodatnoLayout.createSequentialGroup()
                        .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtZaduzenjeID, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelDodatnoLayout.setVerticalGroup(
            jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDodatnoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtZaduzenjeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jbtnSacuvaj)
                .addGap(39, 39, 39))
        );

        jbtnOtkazi.setText("Otkazi");
        jbtnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOtkaziActionPerformed(evt);
            }
        });

        jbtnDodajJos.setText("Dodaj jos Zaduzenja");
        jbtnDodajJos.setRequestFocusEnabled(false);
        jbtnDodajJos.setRolloverEnabled(false);
        jbtnDodajJos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajJosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcomboClanovi, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(84, 84, 84)
                                .addComponent(jcomboFilmovi, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtnDodajJos)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelDodatno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77)
                .addComponent(jPanelTabelaZaduzenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(1182, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTabelaZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcomboClanovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcomboFilmovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnOk)
                            .addComponent(jbtnOtkazi)
                            .addComponent(jbtnDodajJos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelDodatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(602, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboFilmoviItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboFilmoviItemStateChanged
        listaKopija = KontrolerKomunikacije.vratiListuKopija(this);
        listaZaduzenja = KontrolerKomunikacije.uzmiZaduzenja(this);
        List<Kopija> listaZaFilm = new ArrayList<>();
        List<Kopija> listaNevracenih = new ArrayList<>();
        if (listaKopija != null) {
            for (Kopija k : listaKopija) {
                if (k.getFilm().equals(jcomboFilmovi.getSelectedItem())) {
                    listaZaFilm.add(k);
                }
            }
            for (Zaduzenje z : listaZaduzenja) {
                for (Kopija k : listaZaFilm) {
                    if (z.getKopija().equals(k) && z.isStatusZaduzenja().equals("nije vraceno")) {
                        listaNevracenih.add(k);
                    }
                }
            }
            for (Kopija k : listaNevracenih) {
                listaZaFilm.remove(k);
            }
            jtblKopije.setModel(new ModelTabeleKopija(listaZaFilm));

        }
    }//GEN-LAST:event_jcomboFilmoviItemStateChanged

    private void jbtnDodajJosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajJosActionPerformed
//        clan = null;
//        kopija = null;
//        zaduzenje = null;
//        jPanelDodatno.setVisible(false);
//        jPanelTabelaZaduzenja.setVisible(false);
//        jcomboClanovi.setEnabled(true);
//        jcomboFilmovi.setEnabled(true);
//        jbtnOk.setVisible(true);
        popuniFormu();

    }//GEN-LAST:event_jbtnDodajJosActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        Film f = (Film) jcomboFilmovi.getSelectedItem();
        Clan c = (Clan) jcomboClanovi.getSelectedItem();
        Kopija k = ((ModelTabeleKopija) jtblKopije.getModel()).vratiKopiju(0);

        Zaduzenje z = new Zaduzenje();
        z.setClan(c);
        z.setKopija(k);
        z.setZaduzenjeID(jtxtZaduzenjeID.getText());
        z.setRazduzio(null);
        z.setStatusZaduzenja("nije vraceno");
        z.setZaduzio((Radnici) sesija.Sesija.vratiInstancu().getMapa().get("radnik"));

        Date datum = null;
        String datumS = null;
        if (jtxtDatumZaduzenja.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "niste uneli datum razduzenja");
            return;
        } else {
            datumS = jtxtDatumZaduzenja.getText().trim();
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            datum = sdf.parse(datumS);
            z.setDatumZaduzenja(datum);

            boolean b = KontrolerKomunikacije.sacuvajZaduzenje(z, this);
            if (b == true) {
                listaZaduzenja = KontrolerKomunikacije.uzmiListuZaduzenjaZaClana(clan, this);
                jtblZaduzenja.setModel(new ModelTabeleZaduzenja(listaZaduzenja));
                jbtnSacuvaj.setVisible(false);
                jbtnDodajJos.setVisible(true);
                jbtnOtkazi.setVisible(false);
                jbtnOk.setVisible(false);
                otkazi = false;
                jPanelDodatno.setVisible(false);
                jbtnOtkaziIzmenu.setVisible(false);
                JOptionPane.showMessageDialog(this, "uspesno ste uneli zaduzenje");
            } else {
//                JOptionPane.showMessageDialog(this, "niste uspeli da sacuvate");
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti zaduzenje.\n Unesite datum u formatu dd/MM/yyyy");
        }


    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkActionPerformed
        int rbr = jtblKopije.getSelectedRow();
        if (rbr < 0) {
            JOptionPane.showMessageDialog(this, "niste selektovali kopiju");
        } else {
//            film = (Film) jcomboFilmovi.getSelectedItem();
            clan = (Clan) jcomboClanovi.getSelectedItem();
            kopija = ((ModelTabeleKopija) jtblKopije.getModel()).vratiKopiju(rbr);
            zaduzenje = new Zaduzenje();
            zaduzenje.setClan(clan);
            zaduzenje.setKopija(kopija);
            List<Zaduzenje> listaZaduzenja = KontrolerKomunikacije.uzmiListuZaduzenjaZaClana(clan, this);
            popuniID(zaduzenje);
            System.out.println("aaa");
            jbtnOk.setVisible(false);
            jbtnOtkazi.setVisible(true);
            jbtnDodajJos.setVisible(false);
            jPanelTabelaZaduzenja.setVisible(true);
            jPanelDodatno.setVisible(true);
            jtblZaduzenja.setModel(new ModelTabeleZaduzenja(listaZaduzenja));
            jcomboClanovi.setEnabled(false);
            jcomboFilmovi.setEnabled(false);
            List<Kopija> lista = new ArrayList<>();
            lista.add(kopija);
            jtblKopije.setModel(new ModelTabeleKopija(lista));

            otkazi = true;
        }


    }//GEN-LAST:event_jbtnOkActionPerformed

    private void jbtnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOtkaziActionPerformed
        ponistiZaduzenje();
//        jPanelDodatno.setVisible(false);
//        jPanelTabelaZaduzenja.setVisible(false);
//        jbtnOtkazi.setVisible(false);
////        jbtnOk.setVisible(true);
//        jcomboClanovi.setEnabled(true);
//        jcomboFilmovi.setEnabled(true);
//        jbtnOk.setVisible(true);
        popuniFormu();
    }//GEN-LAST:event_jbtnOtkaziActionPerformed

    private void jbtnIzmeniStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniStatusActionPerformed
        int rbr = jtblZaduzenja.getSelectedRow();
        if (rbr < 0) {
            JOptionPane.showMessageDialog(this, "selektujte prvo zaduzenje koje biste da izmenite");
        } else {
//            jbtnDodajJos.setEnabled(false);
            if (((ModelTabeleZaduzenja) jtblZaduzenja.getModel()).vratiZaduzenje(rbr).isStatusZaduzenja().equals("vraceno")) {
                JOptionPane.showMessageDialog(this, "odabrano zaduzenje je vec obradjeno i vraceno");
            } else {
                jtxtDatumRazduzenja.setVisible(true);
                jbtnOtkaziIzmenu.setVisible(true);
                jlbl.setVisible(true);
                jbtnSacuvajIzmenu.setVisible(true);
                jbtnDodajJos.setVisible(false);
            }

        }
    }//GEN-LAST:event_jbtnIzmeniStatusActionPerformed

    private void jbtnSacuvajIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajIzmenuActionPerformed
        Zaduzenje z = ((ModelTabeleZaduzenja) jtblZaduzenja.getModel()).vratiZaduzenje(jtblZaduzenja.getSelectedRow());
        Date datum = null;
        String datumS = null;
        if (jtxtDatumRazduzenja.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "niste uneli datum razduzenja");
            return;
        } else {
            datumS = jtxtDatumRazduzenja.getText().trim();
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            datum = sdf.parse(datumS);
            z.setDatumRazduzenja(datum);
            z.setStatusZaduzenja("vraceno");
            z.setRazduzio((Radnici) sesija.Sesija.vratiInstancu().getMapa().get("radnik"));
            boolean b = KontrolerKomunikacije.sacuvajZaduzenje(z, this);
            if (b == true) {
                listaZaduzenja = KontrolerKomunikacije.uzmiListuZaduzenjaZaClana(clan, this);
                jtblZaduzenja.setModel(new ModelTabeleZaduzenja(listaZaduzenja));
                jlbl.setVisible(false);
                jbtnSacuvajIzmenu.setVisible(false);
                jtxtDatumRazduzenja.setVisible(false);
                jbtnDodajJos.setVisible(true);
                jbtnOtkaziIzmenu.setVisible(false);
                JOptionPane.showMessageDialog(this, "uspesno ste izmenili zaduzenje");
            } else {
//                JOptionPane.showMessageDialog(this, "niste uspeli da sacuvate");
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "unesite datum u formatu dd/MM/yyyy");
        }
    }//GEN-LAST:event_jbtnSacuvajIzmenuActionPerformed

    private void jbtnOtkaziIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOtkaziIzmenuActionPerformed
        jtxtDatumRazduzenja.setVisible(false);
        jtxtDatumRazduzenja.setText("");
        jbtnOtkaziIzmenu.setVisible(false);
        jbtnIzmeniStatus.setVisible(true);
        jbtnSacuvajIzmenu.setVisible(false);
        jlbl.setVisible(false);
        jbtnDodajJos.setVisible(true);
        
    }//GEN-LAST:event_jbtnOtkaziIzmenuActionPerformed

    private void jtblZaduzenjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblZaduzenjaMouseClicked
        if(jtblZaduzenja.getSelectedRow()>=0){
            jbtnIzmeniStatus.setVisible(true);
        }
    }//GEN-LAST:event_jtblZaduzenjaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUnosZaduzenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUnosZaduzenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUnosZaduzenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUnosZaduzenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FUnosZaduzenja dialog = new FUnosZaduzenja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelDodatno;
    private javax.swing.JPanel jPanelTabelaZaduzenja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnDodajJos;
    private javax.swing.JButton jbtnIzmeniStatus;
    private javax.swing.JButton jbtnOk;
    private javax.swing.JButton jbtnOtkazi;
    private javax.swing.JButton jbtnOtkaziIzmenu;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnSacuvajIzmenu;
    private javax.swing.JComboBox jcomboClanovi;
    private javax.swing.JComboBox jcomboFilmovi;
    private javax.swing.JLabel jlbl;
    private javax.swing.JRadioButton jradioDA;
    private javax.swing.JRadioButton jradioNE;
    private javax.swing.JRadioButton jradioSVA;
    private javax.swing.JTable jtblKopije;
    private javax.swing.JTable jtblZaduzenja;
    private javax.swing.JTextField jtxtDatumRazduzenja;
    private javax.swing.JTextField jtxtDatumZaduzenja;
    private javax.swing.JTextField jtxtZaduzenjeID;
    // End of variables declaration//GEN-END:variables

    private void popunComboBoxove() {
        List<Film> listaFilmova = KontrolerKomunikacije.vratiListuFilmova(this);
        if (listaFilmova != null) {
            jcomboFilmovi.removeAllItems();
            for (IDomenskiObjekat m : listaFilmova) {
                jcomboFilmovi.addItem(m);
            }
        } else {
            JOptionPane.showMessageDialog(this, "nije uspeo da vrati listu filmova");
        }

        List<Clan> listaClanova = KontrolerKomunikacije.vratiListuClanova(this);
        if (listaClanova != null) {
            jcomboClanovi.removeAllItems();
            for (IDomenskiObjekat m : listaClanova) {
                jcomboClanovi.addItem(m);
            }
        } else {
            JOptionPane.showMessageDialog(this, "nije uspeo da vrati listu filmova");
        }

    }

    private void popuniID(IDomenskiObjekat ido) {
        String id = KontrolerKomunikacije.vratiNajveciID(ido);
        if (!id.startsWith("nije")) {
            jtxtZaduzenjeID.setText(id);
            zaduzenje.setZaduzenjeID(id);
        } else {
            System.out.println("nije uspeo da primi id");
        }
    }

    private void ponistiZaduzenje() {
        KontrolerKomunikacije.odustani(zaduzenje);

    }

    private void popuniFormu() {
        popunComboBoxove();
        jbtnIzmeniStatus.setVisible(true);
        jbtnSacuvaj.setVisible(true);
        jtxtDatumZaduzenja.setText("");
        jPanelDodatno.setVisible(false);
        jPanelTabelaZaduzenja.setVisible(false);
        jbtnOtkazi.setVisible(false);
        jbtnDodajJos.setVisible(false);
        jtxtZaduzenjeID.setEnabled(false);
        jlbl.setVisible(false);
        jbtnSacuvajIzmenu.setVisible(false);
        jtxtDatumRazduzenja.setVisible(false);
        jcomboClanovi.setEnabled(true);
        jbtnOtkaziIzmenu.setVisible(false);
        jcomboFilmovi.setEnabled(true);
        jbtnOk.setVisible(true);
        zaduzenje = null;
        clan = null;
        kopija = null;
    }

}
