/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.Film;
import domen.IDomenskiObjekat;
import domen.Kopija;
import domen.Mesto;
import domen.Radnici;
import domen.Zaduzenje;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import kontroleri.KontrolerKomunikacije;
import modeli.ModelTabeleKopija;
import modeli.ModelTabeleZaduzenja;
import sesija.Sesija;

/**
 *
 * @author Joca
 */
public class FUnosClana extends javax.swing.JDialog {

    Clan clan;
    boolean ponistiClana = true;
    List<Zaduzenje> listaZaduzenja;
    List<Kopija> listaKopija;
    String radSaZaduzenjem;
    boolean ponistiZaduzenje = false;
    int mod;

    /**
     * Creates new form FUnosClana
     */
    public FUnosClana(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        listaZaduzenja = new ArrayList<>();
        listaKopija = new ArrayList<>();
        popuni();
        jtxtClanID.setEditable(false);
        jbtnDodajJosClanova.setVisible(false);
        listaKopija = new ArrayList<>();
        jradioDA.setVisible(false);
        jradioNE.setVisible(false);
        jradioSVA.setVisible(false);
        mod = 0;
        jbtnIzmeni.setVisible(false);
        Rectangle bounds = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        this.setBounds(bounds);

    }

    public FUnosClana(java.awt.Frame parent, boolean modal, Clan c) {

        super(parent, modal);
        initComponents();
        listaZaduzenja = new ArrayList<>();
        listaKopija = new ArrayList<>();
        clan = c;
        popuniFormuSaPodacima();
        jtxtClanID.setEditable(false);
        jbtnDodajJosClanova.setVisible(false);
        jbtnSacuvaj.setVisible(false);
        listaKopija = new ArrayList<>();
        mod = 1;
        ponistiClana = false;
        ponistiZaduzenje = false;
        podesiPromenuPolja(false);
        Rectangle bounds = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        this.setBounds(bounds);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jradioZaduzenja = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jtxtClanID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtJmbg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDatum = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcomboMesto = new javax.swing.JComboBox();
        jtxtUlicaIBroj = new javax.swing.JTextField();
        jbtnDodajJosClanova = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jPanelTabelaZaduzenja = new javax.swing.JPanel();
        jradioNE = new javax.swing.JRadioButton();
        jradioDA = new javax.swing.JRadioButton();
        jradioSVA = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblZaduzenja = new javax.swing.JTable();
        jbtnDodajZaduzenje = new javax.swing.JButton();
        jbtnIzmeniZaduzenje = new javax.swing.JButton();
        jPanelUnosZaduzenja = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jcomboFilm = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblKopije = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanelDodatno = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtxtZaduzenjeID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtDatumZaduzenja = new javax.swing.JTextField();
        jbtnSacuvajZaduzenje = new javax.swing.JButton();
        jbtnOtkazi = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtxtDatumRazduzenja = new javax.swing.JTextField();
        jbtnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel8.setText("ClanID");

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("JMBG:");

        jtxtJmbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtJmbgActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefon:");

        jLabel5.setText("Datum Uclanjenja:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adresa"));

        jLabel6.setText("Ulica i broj:");

        jLabel7.setText("Mesto:");

        jcomboMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtxtUlicaIBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUlicaIBrojActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcomboMesto, 0, 224, Short.MAX_VALUE)
                    .addComponent(jtxtUlicaIBroj))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtUlicaIBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcomboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnDodajJosClanova.setText("Dodaj jos clanova");
        jbtnDodajJosClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajJosClanovaActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj Clana");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jPanelTabelaZaduzenja.setBorder(javax.swing.BorderFactory.createTitledBorder("Zaduzenja"));

        jradioZaduzenja.add(jradioNE);
        jradioNE.setText("nevracena");
        jradioNE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jradioNEItemStateChanged(evt);
            }
        });

        jradioZaduzenja.add(jradioDA);
        jradioDA.setText("vracena");
        jradioDA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jradioDAItemStateChanged(evt);
            }
        });

        jradioZaduzenja.add(jradioSVA);
        jradioSVA.setSelected(true);
        jradioSVA.setText("sva zaduzenja");
        jradioSVA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jradioSVAItemStateChanged(evt);
            }
        });

        jtblZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblZaduzenja);

        jbtnDodajZaduzenje.setText("Dodaj novo zaduzenje");
        jbtnDodajZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajZaduzenjeActionPerformed(evt);
            }
        });

        jbtnIzmeniZaduzenje.setText("izmeni zaduzenje");
        jbtnIzmeniZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniZaduzenjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabelaZaduzenjaLayout = new javax.swing.GroupLayout(jPanelTabelaZaduzenja);
        jPanelTabelaZaduzenja.setLayout(jPanelTabelaZaduzenjaLayout);
        jPanelTabelaZaduzenjaLayout.setHorizontalGroup(
            jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnDodajZaduzenje, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnIzmeniZaduzenje, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addComponent(jradioSVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jradioDA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jradioNE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTabelaZaduzenjaLayout.setVerticalGroup(
            jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioNE)
                    .addComponent(jradioDA)
                    .addComponent(jradioSVA))
                .addGroup(jPanelTabelaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnDodajZaduzenje))
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTabelaZaduzenjaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jbtnIzmeniZaduzenje)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelUnosZaduzenja.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos/Izmena zaduzenja"));

        jLabel11.setText("Film:");

        jcomboFilm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomboFilm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboFilmItemStateChanged(evt);
            }
        });
        jcomboFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboFilmActionPerformed(evt);
            }
        });

        jtblKopije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblKopije);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Zaduzenje ID:");

        jLabel10.setText("Datum Zaduzenja:");

        jbtnSacuvajZaduzenje.setText("Sacuvaj zaduzenje");
        jbtnSacuvajZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajZaduzenjeActionPerformed(evt);
            }
        });

        jbtnOtkazi.setText("Otkazi");
        jbtnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOtkaziActionPerformed(evt);
            }
        });

        jLabel12.setText("Datum Razduzenja:");

        javax.swing.GroupLayout jPanelDodatnoLayout = new javax.swing.GroupLayout(jPanelDodatno);
        jPanelDodatno.setLayout(jPanelDodatnoLayout);
        jPanelDodatnoLayout.setHorizontalGroup(
            jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDodatnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDodatnoLayout.createSequentialGroup()
                        .addComponent(jbtnSacuvajZaduzenje)
                        .addGap(30, 30, 30)
                        .addComponent(jbtnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDodatnoLayout.createSequentialGroup()
                        .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtZaduzenjeID, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jtxtDatumZaduzenja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jtxtDatumRazduzenja, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelDodatnoLayout.setVerticalGroup(
            jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDodatnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtZaduzenjeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDodatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvajZaduzenje)
                    .addComponent(jbtnOtkazi))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelUnosZaduzenjaLayout = new javax.swing.GroupLayout(jPanelUnosZaduzenja);
        jPanelUnosZaduzenja.setLayout(jPanelUnosZaduzenjaLayout);
        jPanelUnosZaduzenjaLayout.setHorizontalGroup(
            jPanelUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosZaduzenjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUnosZaduzenjaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(30, 30, 30)
                        .addComponent(jcomboFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUnosZaduzenjaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanelDodatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelUnosZaduzenjaLayout.setVerticalGroup(
            jPanelUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnosZaduzenjaLayout.createSequentialGroup()
                .addGroup(jPanelUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUnosZaduzenjaLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jcomboFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUnosZaduzenjaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUnosZaduzenjaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(110, 110, 110))))
                    .addGroup(jPanelUnosZaduzenjaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanelDodatno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(174, 174, 174))
        );

        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jbtnDodajJosClanova)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnSacuvaj))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtDatum)
                            .addComponent(jtxtTelefon)
                            .addComponent(jtxtJmbg)
                            .addComponent(jtxtPrezime)
                            .addComponent(jtxtIme)
                            .addComponent(jtxtClanID, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUnosZaduzenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTabelaZaduzenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnDodajJosClanova)
                            .addComponent(jbtnSacuvaj)
                            .addComponent(jbtnIzmeni)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtClanID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelTabelaZaduzenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanelUnosZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtJmbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtJmbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtJmbgActionPerformed

    private void jtxtUlicaIBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUlicaIBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUlicaIBrojActionPerformed

    private void jbtnDodajJosClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajJosClanovaActionPerformed
        popuniID(new Clan());
        ponistiClana = true;
        jtxtDatum.setText("");
        jtxtIme.setText("");
        jtxtJmbg.setText("");
        jtxtPrezime.setText("");
        jtxtTelefon.setText("");
        jtxtUlicaIBroj.setText("");
        clan = null;
        jbtnDodajJosClanova.setVisible(false);
        jPanelTabelaZaduzenja.setVisible(false);
        jPanelUnosZaduzenja.setVisible(false);
        jbtnIzmeni.setVisible(false);
        jbtnSacuvaj.setVisible(true);
        podesiPromenuPolja(true);
        
    }//GEN-LAST:event_jbtnDodajJosClanovaActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed

        Date datum = null;
        String datumS = null;

        if (jtxtDatum.getText().trim().isEmpty() || jtxtDatum.getText().length()<10) {
            JOptionPane.showMessageDialog(this, "niste uneli lepo datum");
            return;
        } else {
            datumS = jtxtDatum.getText().trim();
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            datum = sdf.parse(datumS);
            clan = new Clan();
            clan.setIme(jtxtIme.getText().trim());
            clan.setJmbg(jtxtJmbg.getText().trim());
            clan.setPrezime(jtxtPrezime.getText().trim());
            clan.setTelefon(jtxtTelefon.getText().trim());
            clan.setUlicaIBroj(jtxtUlicaIBroj.getText().trim());
            clan.setMesto((Mesto) jcomboMesto.getSelectedItem());
            clan.setDatumOsnivanja(datum);
            clan.setClanID(jtxtClanID.getText());
            dodajClana(clan);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "unesite datum u formatu dd/MM/yyyy");
        }


    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnDodajZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajZaduzenjeActionPerformed
//        ponistiZaduzenje= true;
        jPanelUnosZaduzenja.setVisible(true);
        jPanelDodatno.setVisible(false);
        jtblKopije.setEnabled(true);
        jcomboFilm.setEnabled(true);
        popuniPanelUnosZaduzenjaPraznim();
        radSaZaduzenjem = "unos novog";
        jbtnDodajJosClanova.setVisible(false);
        jbtnIzmeni.setVisible(false);

    }//GEN-LAST:event_jbtnDodajZaduzenjeActionPerformed

    private void jbtnIzmeniZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniZaduzenjeActionPerformed
        int rbr = jtblZaduzenja.getSelectedRow();
        if (rbr < 0) {
            JOptionPane.showMessageDialog(this, "niste selektovali zaduzenje koje biste da izmenite");
        } else {
            Zaduzenje z = ((ModelTabeleZaduzenja) jtblZaduzenja.getModel()).vratiZaduzenje(rbr);
            if (z.isStatusZaduzenja().equals("vraceno")) {
                JOptionPane.showMessageDialog(this, "selektovano zaduzenje je vec obradjeno i vraceno");
            } else {
                jPanelUnosZaduzenja.setVisible(true);
                popuniPanelUnosZaduzenje(z);
                radSaZaduzenjem = "izmena";
                jButton1.setVisible(false);
                jcomboFilm.setEnabled(false);
                jtblKopije.setEnabled(false);
                ponistiZaduzenje = false;
                jbtnDodajJosClanova.setVisible(false);
            }
        }
    }//GEN-LAST:event_jbtnIzmeniZaduzenjeActionPerformed

    private void jbtnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOtkaziActionPerformed
        if (radSaZaduzenjem.equals("unos novog")) {
            jPanelUnosZaduzenja.setVisible(false);
            odustaniOdZaduzenja();
            ponistiZaduzenje = false;
            if (mod == 0) {
                jbtnDodajJosClanova.setVisible(true);
            } else {
                jbtnDodajJosClanova.setVisible(false);
            }
        } else {
            jPanelUnosZaduzenja.setVisible(false);
            if (mod == 0) {
                jbtnDodajJosClanova.setVisible(true);
            } else {
                jbtnDodajJosClanova.setVisible(false);
            }
            ponistiZaduzenje = false;
        }
    }//GEN-LAST:event_jbtnOtkaziActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (ponistiClana == true) {
            Clan c = new Clan();
            c.setClanID(jtxtClanID.getText());
            KontrolerKomunikacije.odustani(c);
        }
        if (ponistiZaduzenje == true) {
            odustaniOdZaduzenja();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jbtnSacuvajZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajZaduzenjeActionPerformed
        Zaduzenje z = new Zaduzenje(); 
        if (radSaZaduzenjem.equals("izmena")) {
            Date datum = null;
            String datumS = null;
            if (jtxtDatumRazduzenja.getText().trim().isEmpty() || jtxtDatumRazduzenja.getText().length()<10) {
                JOptionPane.showMessageDialog(this, "niste lepo uneli datum razduzenja");
                return;
            } else {
                datumS = jtxtDatumRazduzenja.getText().trim();
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                datum = sdf.parse(datumS);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "unesite datum u formatu dd/MM/yyyy");
            }

            z.setDatumRazduzenja(datum);
            z.setRazduzio((Radnici)Sesija.vratiInstancu().getMapa().get("radnik"));
            
        }

        z.setZaduzenjeID(jtxtZaduzenjeID.getText());
        z.setClan(clan);
        if(radSaZaduzenjem.equals("izmena")){
            Zaduzenje zz = ((ModelTabeleZaduzenja)jtblZaduzenja.getModel()).vratiZaduzenje(jtblZaduzenja.getSelectedRow());
            z.setZaduzio(zz.getZaduzio());
        }else{
            z.setZaduzio((Radnici) Sesija.vratiInstancu().getMapa().get("radnik"));
        }
        z.setStatusZaduzenja("nije vraceno");
        Date datum = null;
        String datumS = null;
        if (jtxtDatumZaduzenja.getText().trim().isEmpty() || jtxtDatumZaduzenja.getText().trim().length()<10) {
            JOptionPane.showMessageDialog(this, "niste lepo uneli datum");
            return;
        } else {
            datumS = jtxtDatumZaduzenja.getText().trim();
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            datum = sdf.parse(datumS);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "unesite datum u formatu dd/MM/yyyy");
        }

        z.setDatumZaduzenja(datum);
        Kopija k = new Kopija();
        int rbr = jtblKopije.getSelectedRow();
        if (rbr < 0 && !radSaZaduzenjem.equals("izmena")) {
            JOptionPane.showMessageDialog(this, "niste selektovali kopije");
        } else {
            if (radSaZaduzenjem.equals("izmena")) {
                k = ((ModelTabeleKopija) jtblKopije.getModel()).vratiKopiju(0);
                z.setStatusZaduzenja("vraceno");
            } else {
                k = ((ModelTabeleKopija) jtblKopije.getModel()).vratiKopiju(rbr);
                z.setStatusZaduzenja("nije vraceno");
            }
            k.setFilm((Film) jcomboFilm.getSelectedItem());
            z.setKopija(k);
            boolean b = sacuvajZaduzenje(z);

            if (b == true) {
                jPanelUnosZaduzenja.setVisible(false);
                if (mod == 0) {
                    jbtnDodajJosClanova.setVisible(true);
                } else {
                    jbtnDodajJosClanova.setVisible(false);
                }
                jbtnSacuvaj.setVisible(false);
                List<Zaduzenje> lista = KontrolerKomunikacije.uzmiListuZaduzenjaZaClana(clan, this);
                jtblZaduzenja.setModel(new ModelTabeleZaduzenja(lista));
                JOptionPane.showMessageDialog(this, "uspesno ste uneli zaduzenje");
            } else {
//                JOptionPane.showMessageDialog(this, "niste uspeli da sacuvate");
            }

        }


    }//GEN-LAST:event_jbtnSacuvajZaduzenjeActionPerformed

    private void jcomboFilmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboFilmItemStateChanged
        System.out.println("ITEMSTATECHANGED");
        Film f = (Film) jcomboFilm.getSelectedItem();
        listaKopija = KontrolerKomunikacije.vratiListuKopija(this);
        listaZaduzenja = KontrolerKomunikacije.uzmiZaduzenja(this);
        List<Kopija> listaKopijaZaFilm = new ArrayList<>();
        List<Kopija> listaNedostupnih = new ArrayList<>();
        for (Kopija k : listaKopija) {
            if (k.getFilm().equals(f)) {
                listaKopijaZaFilm.add(k);
            }
        }
        for (Zaduzenje z : listaZaduzenja) {
            for (Kopija k : listaKopijaZaFilm) {
                if ((z.getKopija().equals(k)) && z.isStatusZaduzenja().startsWith("nije")) {
                    listaNedostupnih.add(k);
                }
            }
        }
        for (Kopija k : listaNedostupnih) {
            listaKopijaZaFilm.remove(k);
        }
        jtblKopije.setModel(new ModelTabeleKopija(listaKopijaZaFilm));
    }//GEN-LAST:event_jcomboFilmItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Zaduzenje z = new Zaduzenje();
        z.setClan(clan);
        int rbr = jtblKopije.getSelectedRow();
        if (rbr >= 0) {
            Kopija k = ((ModelTabeleKopija) jtblKopije.getModel()).vratiKopiju(rbr);
            k.setFilm((Film) jcomboFilm.getSelectedItem());
            z.setKopija(k);
            z.setStatusZaduzenja("nije vraceno");
            popuniID(z);
            jPanelDodatno.setVisible(true);
            jtxtZaduzenjeID.setEditable(false);
            jLabel12.setVisible(false);
            jtxtDatumRazduzenja.setVisible(false);
            jButton1.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this, "selektujte prvo kopiju");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcomboFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboFilmActionPerformed

    private void jradioSVAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jradioSVAItemStateChanged
        if (jradioSVA.isSelected()) {
            jtblZaduzenja.setModel(new ModelTabeleZaduzenja(listaZaduzenja));
        }
    }//GEN-LAST:event_jradioSVAItemStateChanged

    private void jradioDAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jradioDAItemStateChanged
        if (jradioDA.isSelected()) {
            List<Zaduzenje> vracena = new ArrayList<Zaduzenje>();
            for (Zaduzenje z : listaZaduzenja) {
                if (z.isStatusZaduzenja().equals("vraceno")) {
                    vracena.add(z);
                }
            }
            jtblZaduzenja.setModel(new ModelTabeleZaduzenja(vracena));
        }
    }//GEN-LAST:event_jradioDAItemStateChanged

    private void jradioNEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jradioNEItemStateChanged
        if (jradioNE.isSelected()) {
            List<Zaduzenje> nijeVraceno = new ArrayList<Zaduzenje>();
            for (Zaduzenje z : listaZaduzenja) {
                if (z.isStatusZaduzenja().startsWith("n")) {
                    nijeVraceno.add(z);
                }
            }
            jtblZaduzenja.setModel(new ModelTabeleZaduzenja(nijeVraceno));
        }
    }//GEN-LAST:event_jradioNEItemStateChanged

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
//        Date datum = null;
//        String datumS = null;
//
//        if (jtxtDatum.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "niste uneli datum");
//            return;
//        } else {
//            datumS = jtxtDatum.getText().trim();
//        }
//
//        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//        try {
//            datum = sdf.parse(datumS);
//            clan = new Clan();
//            clan.setIme(jtxtIme.getText().trim());
//            clan.setJmbg(jtxtJmbg.getText().trim());
//            clan.setPrezime(jtxtPrezime.getText().trim());
//            clan.setTelefon(jtxtTelefon.getText().trim());
//            clan.setUlicaIBroj(jtxtUlicaIBroj.getText().trim());
//            clan.setMesto((Mesto) jcomboMesto.getSelectedItem());
//            clan.setDatumOsnivanja(datum);
//            clan.setClanID(jtxtClanID.getText());
//            dodajClana(clan);
//        } catch (ParseException ex) {
//            JOptionPane.showMessageDialog(this, "unesite datum u formatu dd/MM/yyyy");
//        }
        podesiPromenuPolja(true);
        jbtnSacuvaj.setVisible(true);
        jbtnDodajJosClanova.setVisible(false);
        jbtnIzmeni.setVisible(false);

    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUnosClana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUnosClana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUnosClana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUnosClana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FUnosClana dialog = new FUnosClana(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDodatno;
    private javax.swing.JPanel jPanelTabelaZaduzenja;
    private javax.swing.JPanel jPanelUnosZaduzenja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnDodajJosClanova;
    private javax.swing.JButton jbtnDodajZaduzenje;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnIzmeniZaduzenje;
    private javax.swing.JButton jbtnOtkazi;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnSacuvajZaduzenje;
    private javax.swing.JComboBox jcomboFilm;
    private javax.swing.JComboBox jcomboMesto;
    private javax.swing.JRadioButton jradioDA;
    private javax.swing.JRadioButton jradioNE;
    private javax.swing.JRadioButton jradioSVA;
    private javax.swing.ButtonGroup jradioZaduzenja;
    private javax.swing.JTable jtblKopije;
    private javax.swing.JTable jtblZaduzenja;
    private javax.swing.JTextField jtxtClanID;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtDatumRazduzenja;
    private javax.swing.JTextField jtxtDatumZaduzenja;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtJmbg;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JTextField jtxtTelefon;
    private javax.swing.JTextField jtxtUlicaIBroj;
    private javax.swing.JTextField jtxtZaduzenjeID;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {
        List<Mesto> listaMesta = KontrolerKomunikacije.vratiListuMesta(this);
        if (listaMesta != null) {
            jcomboMesto.removeAllItems();
            for (IDomenskiObjekat m : listaMesta) {
                jcomboMesto.addItem(m);
            }
        } else {
            JOptionPane.showMessageDialog(this, "nije uspeo da vrati mesta");
        }
    }

    private void dodajClana(Clan clan) {
        String b = KontrolerKomunikacije.dodajClana(clan);
        if (b.equals("ok")) {
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio clana");
            if (mod == 0) {
                jbtnDodajJosClanova.setVisible(true);
            } else {
                jbtnDodajJosClanova.setVisible(false);
            }
            ponistiClana = false;
            jbtnSacuvaj.setVisible(false);
            jtblZaduzenja.setModel(new ModelTabeleZaduzenja(listaZaduzenja));
            jPanelTabelaZaduzenja.setVisible(true);
            jbtnIzmeni.setVisible(true);
            podesiPromenuPolja(false);
        } else {
            JOptionPane.showMessageDialog(this, "niste sacuvali clana, doslo je do greske : " + b);
        }

    }

    private void popuniPodatke() {
        jtxtClanID.setText(clan.getClanID());
        jtxtIme.setText(clan.getIme());
        jtxtJmbg.setText(clan.getJmbg());
        jtxtPrezime.setText(clan.getPrezime());
        jtxtTelefon.setText(clan.getTelefon());
        jtxtUlicaIBroj.setText(clan.getUlicaIBroj());
        jtxtDatum.setText(new SimpleDateFormat("dd/MM/yyyy").format(clan.getDatumOsnivanja()));
        ponistiClana = false;
    }

    private void popuniID(IDomenskiObjekat ido) {
        String id = KontrolerKomunikacije.vratiNajveciID(ido);
        if (!id.startsWith("nije")) {
            if (ido instanceof Clan) {
                jtxtClanID.setText(id);
            } else {
                jtxtZaduzenjeID.setText(id);
            }
        } else {
            System.out.println("nije uspeo da primi id");
        }
    }

    private void popuni() {
        popuniID(new Clan());
        jPanelUnosZaduzenja.setVisible(false);
        jPanelTabelaZaduzenja.setVisible(false);
        popuniCombo();
    }

    private void popuniPanelUnosZaduzenje(Zaduzenje z) {
        jtxtZaduzenjeID.setText(z.getZaduzenjeID());
        jtxtDatumRazduzenja.setVisible(true);
        jLabel12.setVisible(true);
        Date d = z.getDatumZaduzenja();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dat = sdf.format(d);
        jtxtDatumZaduzenja.setText(dat);
        popuniComboFilm();
        jcomboFilm.setSelectedItem(z.getKopija().getFilm());
        jtxtZaduzenjeID.setEditable(false);
        popuniListuKopija();
        List<Kopija> lista = new ArrayList<>();
        for (Kopija k : listaKopija) {
            if (k.equals(z.getKopija())) {
                lista.add(k);
            }
        }
        jtblKopije.setModel(new ModelTabeleKopija(lista));

    }

    private void popuniListuKopija() {
        listaKopija = KontrolerKomunikacije.vratiListuKopija(this);
        if (listaKopija != null) {
        } else {
            JOptionPane.showMessageDialog(this, "nije uspeo da vrati kopije");
        }
    }

    private void popuniPanelUnosZaduzenjaPraznim() {
//        Zaduzenje z = new Zaduzenje();
//        z.setClan(clan);
//        popuniID(z);
        jtxtDatumZaduzenja.setText("");
        popuniComboFilm();
        Film f = (Film) jcomboFilm.getSelectedItem();
        listaKopija = KontrolerKomunikacije.vratiListuKopija(this);
        List<Kopija> listaNedostupnih = new ArrayList<>();
        List<Zaduzenje> listaZaduzenja = KontrolerKomunikacije.uzmiZaduzenja(this);
        for (Zaduzenje z : listaZaduzenja) {
            for (Kopija k : listaKopija) {
                if (z.getKopija().equals(k) && z.isStatusZaduzenja().equals("nije vraceno")) {
                    listaNedostupnih.add(k);
                }
            }
        }
        for (Kopija k : listaNedostupnih) {
            listaKopija.remove(k);
        }

        List<Kopija> listaKopijaZaFilm = new ArrayList<>();
        for (Kopija k : listaKopija) {
            if (k.getFilm().equals(f)) {
                listaKopijaZaFilm.add(k);
            }
        }

        jtblKopije.setModel(new ModelTabeleKopija(listaKopijaZaFilm));
        jButton1.setVisible(true);
//        jtxtZaduzenjeID.setEditable(false);

    }

    private void popuniComboFilm() {
        List<Film> listaFilmova = KontrolerKomunikacije.vratiListuFilmova(this);
        if (listaFilmova != null) {
            jcomboFilm.removeAllItems();
            for (IDomenskiObjekat m : listaFilmova) {
                jcomboFilm.addItem(m);
            }
        } else {
            JOptionPane.showMessageDialog(this, "nije uspeo da vrati listu filmova");
        }
    }

    private void odustaniOdZaduzenja() {
        Zaduzenje z = new Zaduzenje();
        z.setClan(clan);
        z.setZaduzenjeID(jtxtZaduzenjeID.getText());
        Kopija k = new Kopija();
        k = ((ModelTabeleKopija) jtblKopije.getModel()).vratiKopiju(jtblKopije.getSelectedRow());
        Film f = new Film();
        f.setFilmID(((Film) jcomboFilm.getSelectedItem()).getFilmID());
        k.setFilm(f);
        z.setKopija(k);
        KontrolerKomunikacije.odustani(z);
    }

    private boolean sacuvajZaduzenje(Zaduzenje z) {
        return KontrolerKomunikacije.sacuvajZaduzenje(z, this);
    }

    private void popuniFormuSaPodacima() {
        jtxtClanID.setText(clan.getClanID());
        Date d = clan.getDatumOsnivanja();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dat = sdf.format(d);
        jtxtDatum.setText(dat);
        jtxtIme.setText(clan.getIme());
        jtxtJmbg.setText(clan.getJmbg());
        jtxtPrezime.setText(clan.getPrezime());
        jtxtTelefon.setText(clan.getTelefon());
        jtxtUlicaIBroj.setText(clan.getUlicaIBroj());
        listaZaduzenja = KontrolerKomunikacije.uzmiListuZaduzenjaZaClana(clan, this);
        jtblZaduzenja.setModel(new ModelTabeleZaduzenja(listaZaduzenja));
        popuniCombo();
        jPanelUnosZaduzenja.setVisible(false);
    }

    private void podesiPromenuPolja(boolean b) {
        jtxtIme.setEditable(b);
        jtxtPrezime.setEditable(b);
        jtxtDatum.setEditable(b);
        jtxtJmbg.setEditable(b);
        jtxtTelefon.setEditable(b);
        jtxtUlicaIBroj.setEditable(b);
        jcomboMesto.setEditable(b);
    }

}
